### ISSUE TITLE
Old nest check fails to submit

### ISSUE THREAD

**Issue by bpqle** [melizalab/django-bird-colony#43]
After getting a 500 error on the new nest check form, I tried to put in the same nest check (6/15/24) in the old form. The form couldn't be submitted because 2 nest locations had errors:
 - R3 has 'location has >1 adult female'
 - R8 has 'location has >1 adult male'
The location summary only shows 1 male and 1 female listed for either of these nests.

**Comment by dmeliza** [comment]
This is a deprecated feature that will be removed as soon as we're satisfied the new form is working properly, so I'm probably not going to fix this.
